import pandas as pd
data = pd.read_excel("datasets/report_generator.xlsx")

import win32com.client as win32
outlook = win32.Dispatch('outlook.application')

import os
from os.path import join

import time
start = time.time()

import re

for training in data['training'].unique():
    train_base = data[data['training'] == training]
    for date_start in train_base['waktu'].unique():
        date_base = train_base[train_base['waktu'] == date_start]
        table_1 = date_base[['training', 'trainer', 'waktu']].set_index('training')
        table_1 = table_1.transpose()
        table_2 = date_base[['peserta', 'dept', 'atasan', 'Post test', 'Kehadiran']]
        ts = pd.to_datetime(str(date_start))
        d = ts.strftime('%Y-%m-%d %H:%M')
        # --email
        mail = outlook.CreateItem(0)
        mail.Subject = "Report | " + training
        for recipient in date_base['email_optional'].unique():
            mail.Recipients.Add(recipient)
        for carbon in date_base['email_trainer'].unique():
            cc = mail.Recipients.Add(carbon)
            cc.Type = 2
        default = mail.Recipients.Add('prameswari.kristal@nutrifood.co.id')
        default.Type = 2
        total_id_1 = 'totalID1'
        header_id_1 = 'headerID1'
        total_id_2 = 'totalID2'
        header_id_2 = 'headerID2'
        style_1_in_html = """<style>table#{total_table} {{color='black';font-size:13px; text-align:left; border:0.2px solid black; border-collapse:collapse; table-layout:fixed; padding:10px; width=100%; height="250"; text-align:left}} thead#{header_table} {{background-color: #fff645; color:#000000}}</style>""".format(total_table=total_id_1, header_table=header_id_1)
        style_2_in_html = """<style>table#{total_table} {{color='black';font-size:13px; text-align:center; border:0.2px solid black; border-collapse:collapse; table-layout:fixed; padding:10px; width=100%; height="250"; text-align:center}} thead#{header_table} {{background-color: #fff645; color:#000000}}</style>""".format(total_table=total_id_2, header_table=header_id_2)
        table_1_in_html = table_1.to_html()
        table_1_in_html = re.sub(r'<table', r'<table id=%s ' % total_id_1, table_1_in_html)
        table_1_in_html = re.sub(r'<thead', r'<thead id=%s ' % header_id_1, table_1_in_html)
        table_2_in_html = table_2.to_html(index=False)
        table_2_in_html = re.sub(r'<table', r'<table id=%s ' % total_id_2, table_2_in_html)
        table_2_in_html = re.sub(r'<thead', r'<thead id=%s ' % header_id_2, table_2_in_html)
        body1 = "<p>Dear rekan-rekan leader,<br/>Berikut adalah report dari pelaksanaan training:<br/></p>"
        body2 = style_1_in_html + table_1_in_html
        body3 = style_2_in_html + table_2_in_html
        body4 = "<p>Terimakasih,<br/><br/>Generated by pyYDL any issue please inform prameswari.kristal@nutrifood.co.id<br/></p>"
        body5 = "<br/>"
        mail.HTMLBody = body1 + body2 + body5 + body3 + body4
        mail.Send()
        
        print("Report training " + training + "tanggal " + str(d) + " sudah terkirim.")
        
end = time.time()
durasi = (end - start)
print("Total seluruh proses " + str(durasi) + " detik")
input("Press enter to exit")